# prometheus/prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3000']
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:9000']
  # Add other services here
